
development:
  adapter: postgresql
  encoding: unicode
  database: dnuba_development
  pool: 5
  username: postgres 
  password: Servidual2016
  host: localhost
  port: 5432



test:
  adapter: postgresql
  encoding: unicode
  database: dnuba_test
  pool: 5
  username: postgres 
  password: Servidual2016
  host: localhost
  port: 5432
  

production:
  adapter: postgresql
  encoding: unicode
  database: dnuba_production
  pool: 5
  username: postgres
  password: alejo0906
  host: localhost
  port: 5432
